export const ACHIEVEMENT_POLICY_VERSION = 1;

export const ACHIEVEMENT_CATEGORIES = [
  "DISCIPLINE",
  "STREAK",
  "WORKOUT",
  "PROGRESSION",
  "CONSISTENCY",
  "PROTOCOL",
  "TRANSFORMATION",
] as const;
export type AchievementCategory = (typeof ACHIEVEMENT_CATEGORIES)[number];

export const SYSTEM_TITLES = [
  "SYSTEM INITIATE",
  "DISCIPLINED",
  "UNBROKEN",
  "ASCENDANT",
  "IRON CONSISTENCY",
  "RISING",
  "ELITE",
  "APEX",
  "TRANSCENDENT",
] as const;
export type SystemTitle = (typeof SYSTEM_TITLES)[number];

export const ACHIEVEMENT_DEFINITIONS = [
  {
    key: "FIRST_CLEAR",
    name: "FIRST CLEAR",
    description: "Complete the first Perfect Day.",
    category: "DISCIPLINE",
    metric: "perfectDays",
    target: 1,
    titleReward: "SYSTEM INITIATE",
    order: 1,
  },
  {
    key: "PERFECT_STREAK_7",
    name: "SEVEN DAY DISCIPLINE",
    description: "Reach a 7-day Perfect Day streak.",
    category: "STREAK",
    metric: "perfectStreak",
    target: 7,
    titleReward: "DISCIPLINED",
    order: 2,
  },
  {
    key: "PERFECT_STREAK_14",
    name: "FOURTEEN DAY DISCIPLINE",
    description: "Reach a 14-day Perfect Day streak.",
    category: "STREAK",
    metric: "perfectStreak",
    target: 14,
    titleReward: "UNBROKEN",
    order: 3,
  },
  {
    key: "PERFECT_STREAK_30",
    name: "THIRTY DAY DISCIPLINE",
    description: "Reach a 30-day Perfect Day streak.",
    category: "STREAK",
    metric: "perfectStreak",
    target: 30,
    titleReward: "ASCENDANT",
    order: 4,
  },
  {
    key: "HYDRATION_STREAK_7",
    name: "HYDRATION STREAK",
    description: "Clear Hydration for 7 consecutive eligible days.",
    category: "CONSISTENCY",
    metric: "hydrationStreak",
    target: 7,
    order: 5,
  },
  {
    key: "SLEEP_STREAK_7",
    name: "SLEEP STREAK",
    description: "Clear Sleep for 7 consecutive eligible days.",
    category: "CONSISTENCY",
    metric: "sleepStreak",
    target: 7,
    order: 6,
  },
  {
    key: "NO_JUNK_STREAK_7",
    name: "CLEAN WEEK",
    description: "Clear No Junk Food for 7 consecutive eligible days.",
    category: "CONSISTENCY",
    metric: "noJunkStreak",
    target: 7,
    order: 7,
  },
  {
    key: "NO_FAP_STREAK_7",
    name: "CONTROL",
    description: "Clear the configured No Fap habit for 7 consecutive eligible days.",
    category: "CONSISTENCY",
    metric: "noFapStreak",
    target: 7,
    order: 8,
  },
  {
    key: "STEPS_STREAK_7",
    name: "MOVEMENT STREAK",
    description: "Clear Steps for 7 consecutive eligible days.",
    category: "CONSISTENCY",
    metric: "stepsStreak",
    target: 7,
    order: 9,
  },
  {
    key: "WORKOUT_WEEK_SECURED_1",
    name: "FIRST WEEK SECURED",
    description: "Secure the first weekly workout mission.",
    category: "WORKOUT",
    metric: "securedWorkoutWeeks",
    target: 1,
    order: 10,
  },
  {
    key: "WORKOUT_WEEK_STREAK_4",
    name: "FOUR WEEK TRAINING STREAK",
    description: "Secure 4 consecutive workout weeks.",
    category: "WORKOUT",
    metric: "workoutWeekStreak",
    target: 4,
    titleReward: "IRON CONSISTENCY",
    order: 11,
  },
  {
    key: "LEVEL_5",
    name: "LEVEL 5",
    description: "Reach System Level 5.",
    category: "PROGRESSION",
    metric: "level",
    target: 5,
    order: 12,
  },
  {
    key: "LEVEL_10",
    name: "LEVEL 10",
    description: "Reach System Level 10.",
    category: "PROGRESSION",
    metric: "level",
    target: 10,
    titleReward: "RISING",
    order: 13,
  },
  {
    key: "LEVEL_20",
    name: "LEVEL 20",
    description: "Reach System Level 20.",
    category: "PROGRESSION",
    metric: "level",
    target: 20,
    titleReward: "ELITE",
    order: 14,
  },
  {
    key: "RANK_A",
    name: "RANK A",
    description: "Reach System Rank A.",
    category: "PROGRESSION",
    metric: "level",
    target: 21,
    order: 15,
  },
  {
    key: "RANK_S",
    name: "RANK S",
    description: "Reach System Rank S.",
    category: "PROGRESSION",
    metric: "level",
    target: 26,
    titleReward: "APEX",
    order: 16,
  },
  {
    key: "RANK_S_PLUS",
    name: "RANK S+",
    description: "Reach System Rank S+.",
    category: "PROGRESSION",
    metric: "level",
    target: 31,
    titleReward: "TRANSCENDENT",
    order: 17,
  },
  {
    key: "DAY_30_ACTIVE",
    name: "FIRST ASCENT",
    description: "Reach Day 30 with tracked participation.",
    category: "PROTOCOL",
    metric: "day30Active",
    target: 1,
    order: 18,
  },
  {
    key: "DAY_60_ACTIVE",
    name: "DEEP WINTER",
    description: "Reach Day 60 with tracked participation.",
    category: "PROTOCOL",
    metric: "day60Active",
    target: 1,
    order: 19,
  },
  {
    key: "DAY_90_COMPLETE",
    name: "WINTER ARC COMPLETE",
    description: "Complete the protocol with tracked participation.",
    category: "PROTOCOL",
    metric: "day90Complete",
    target: 1,
    order: 20,
  },
  {
    key: "PERFECT_WEEK",
    name: "PERFECT WEEK",
    description: "Clear every day in a finalized full challenge week.",
    category: "DISCIPLINE",
    metric: "perfectWeeks",
    target: 1,
    order: 21,
  },
] as const;

export type AchievementDefinition = (typeof ACHIEVEMENT_DEFINITIONS)[number];
export type AchievementKey = AchievementDefinition["key"];
export type AchievementMetric = AchievementDefinition["metric"];

export function getAchievementDefinition(key: string) {
  return ACHIEVEMENT_DEFINITIONS.find((definition) => definition.key === key) ?? null;
}
